# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ryphon
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: vlan
service: vlan-flask

provider:
  name: aws
  runtime: python3.12
  architecture: x86_64
  memorySize: 256
  timeout: 30
  stage: prod
  region: us-west-2
  environment:
    PYTHONPATH: /var/runtime
  iam:
    role: arn:aws:iam::456410706824:role/vlan-flask-sls
  httpApi:
    cors: true

package:
  patterns:
    - '!node_modules/**'
    - '!.git/**'
    - '!__pycache__/**'
    - '!.pytest_cache/**'
    - '!*.pyc'

functions:
  app:
    handler: wsgi_handler.handler
    memorySize: 256
    timeout: 30
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

custom:
  wsgi:
    app: app.app
    pythonBin: python3
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    strip: false
    usePoetry: false
    useStaticCache: true
    useDownloadCache: true
  customDomain:
    domainName: api.itisamystery.com
    stage: prod
    certificateName: '*.itisamystery.com'
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: http

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-domain-manager
